name: Build addon

on:
  push:

env:
  TARGET: nextcloud_backup
  # IMAGE: "{arch}-hassio-nextcloud-backup"
  IMAGE: test-{arch}
  # REPOSITORY: sebclemhassaddon
  REPOSITORY: brokenfire


jobs:
  armhf:
    runs-on: ubuntu-latest
    env:
      BUILD_ARCH: armhf
    steps:
    - uses: actions/checkout@v2
    
    - name: test-
      uses: Sebclem/action_hassio_addon_builder@1.0.0




    
